### ISSUE TITLE
Integrate with KeePass update checker

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#16]
Today I noticed that the Word Sequencer displays "?" for a version in the KeePass update checker, although it's possible that's because I built my own DLL:

![keepass_update_check](https://cloud.githubusercontent.com/assets/1334420/9308539/51236e22-44ca-11e5-989c-b16e7c677821.png)

That looks fairly easy to fix, it mostly means updating a .txt file with each release, and adding a function to the plugin to point to it: http://keepass.info/help/v2_dev/plg_index.html#upd

**Comment by fireout** [comment]
resolved with pr #21
