### ISSUE TITLE
Remove options that decrease password security?

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#22]
I was thinking about the "length strength" for characters and percentage options for words, and it seems that these options add a tiny bit more randomness, for big potential sacrifices in password security. I asked on the Security Stack Exchange about the [entropy calculation for variable-length password generation schemes](http://security.stackexchange.com/q/107236/93625) for my entropy bar branch (almost done, sorry I've been busy for a while) and confirmed that these options probably are not worth using.

Is there any reason to include these, aside from backwards compatibility? I think the interface for setting these should probably be removed, if not the capability itself.

The only way I could see these being useful, would be for an either-or type of sequence item (e.g. choose a word from list 1 with 50% probability, otherwise choose a word from list 2), but the options would need reworking to support that anyway. Right now I think the options just complicate the interface, and sacrifice security.

**Comment by fireout** [comment]
I'm not against removing length strength; how about Probability, is this one also an issue?

I still would leave the possibility of defining those "advanced" feature though the configuration file though, maybe with a disclaimer or message, when loading a file with them?

**Comment by fritzophrenic** [comment]
Yes, leaving off a word or a letter sometimes just makes the average generated password weaker.

Consider an extreme case: a password with the static word "password" followed by 20 words, each of which has a 1% chance of being included, selecting from a list of 10000. While technically the random chance of including or excluding certain words adds some randomness to the password generation, which increases the number of guesses a naive attacker would need if they knew the method used for password generation, the generated password has about an 82% chance of being just "password" and nearly a 0% chance of being an uncrackable 10,000^20 random possibilities. Such a sequence could not really be called "secure".

In less extreme cases, you still get far more benefit from simply always including an item, than any randomness you may add by including/excluding that item.

I like the idea of keeping the option available in the XML (I think I'm already done with the entropy calculation), but I think including it in the GUI is not useful and just makes it more complicated to use. So let's keep support in the code but not in the GUI unless somebody specifically asks for it and isn't deterred by the "reduces security" argument.
