### ISSUE TITLE
plugin incompatible error message

### ISSUE THREAD

**Issue by TimetravelerDD** [fireout/keepasssequencer#24]
Dear fireout,

First of all: Thank you for the recent release – I look very much forward to try it out! However I would like to ask you if you could kindly help me to troubleshoot one issue. When I try to start it, I get the following Error:

![keepass_3](https://cloud.githubusercontent.com/assets/14355674/12512579/78f3fa86-c119-11e5-9e0d-97aef70748b2.png)

I will try to report some relevant info about my system. Please tell me if you need more
Keepass 2.31
Path: C:\Program Files (x86)\KeePass Password Safe 2
Windows 10 Pro x64 Version 1511 
Build 10586.63
Thinkpad T420 / i5-2520M / 16 GB / 512GB SSD (Crucial_CT512MX100SSD1)

**Comment by fireout** [comment]
Hello TimetravelerDD,

I'm sorry, this is my mistake, I wanted to make it clear that the release was an alpha release, but Keepass expects the plugin classes to match the filename of the dll.

I moved and renamed [Sequencer.dll](https://github.com/fireout/keepasssequencer/blob/master/release/0.1-alpha/Sequencer.dll) so it's properly named.

Please download or rename it on your system and confirm if this was the only issue.

**Comment by TimetravelerDD** [comment]
Hello fireout,

thank you for this advice – it is now properly starting :-)
I am happy to test it. The plugin interface looks good and I like that you can load preconfigured word lists. But when I try to load a standard list (e.g diceware) it throws an exception. The same happens if I try to save any configuration. I assumed this had something to do with protected write access, however it also appears if I started Keepass as admin. Would it be a solution to store the plugin settings in the appdata folder like the keepass main application does?

Maybe this will tell you something (sorry it is German):
########################################

`Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

*************\* Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Sequencer.Sequencer.InsertProfileNameInPath(String path, String profileName)
   bei Sequencer.Sequencer.GetConfigurationPath(Boolean getPathForWrite, String profileName)
   bei Sequencer.Sequencer.Load(String profileName)
   bei Sequencer.Forms.MainForm.AppendWordListFromProfile(String profile)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1063.1 built by: NETFXREL3STAGE.

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.

KeePass
    Assembly-Version: 2.31.0.27913.
    Win32-Version: 2.31.0.0.

##     CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe.

System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.

System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.

System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.

System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.

System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.

System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.

System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.

Sequencer
    Assembly-Version: 0.1.0.0.
    Win32-Version: 0.1.0.0.

##     CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/Sequencer.DLL.

KeePass.XmlSerializers
    Assembly-Version: 2.31.0.27913.
    Win32-Version: 2.31.0.27913.

##     CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL.

System.Security
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll.

mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.

*************\* JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by fireout** [comment]
It's actually a path problem, the default path is the execution folder (usually program files) which we probably dont have access to, but you can specify the path in a dll configuration file.  I included a default config file in the release folder (my mistake, sorry again). Can you tell me if it work with this now?  I realize I could probably make it save in the user local app settings by default though.  

The additionnal word files are not packaged with the dll yet, but I can probably do this in the coming days.

I'm also happy you are taking the time to help :)

**Comment by fritzophrenic** [comment]
Oops, I forgot to mention in the pull request you made, the special characters (especially '&') need to be escaped in the word lists you have in the repo at the moment, e.g. "&amp;amp;".

Also, with a release out, we should really get the update check integration working. :-)

**Comment by TimetravelerDD** [comment]
Hello,
starting up works great! No exceptions thrown during loading and saving. Very smooth!
Word lists are not included as you pointed out.
Settings are remembered even after closing and restarting (how is it possible? Where are they saved?)

The interface takes some time to fully understand, but as a nerd I can live with that :-D

**Comment by fireout** [comment]
Hello Again,

> The interface takes some time to fully understand, but as a nerd I can live with that :-D

Can you have a look at the [wiki](https://github.com/fireout/keepasssequencer/wiki/2.-Basic-Configuration)?   It may help understand the interface.  Also, any suggestion is welcome :)

> Settings are remembered even after closing and restarting (how is it possible? Where are they saved?)

Settings are saved within a file at `%APPDATA%\Keepass`, but you can specify a full path and name in the Sequencer.DLL.Config and the files will be saved there.

I packaged the word list in the dll directly yesterday, I also included the update check (as mentionned by @fritzophrenic and in #16).  I still have to look at escaping the &...  I have some time in the comming days, I will probably get this going a bit and package another release.

Hope this help, thanks again

**Comment by fireout** [comment]
fyi: I pushed a new alpha release with the keepass update check and packaged word list.

**Comment by TimetravelerDD** [comment]
Dear fireout,
I downloaded the new files. When I try to use it i got the following error:
![error reading configuration](https://cloud.githubusercontent.com/assets/14355674/12537831/cc55ddaa-c2c9-11e5-90c5-0bf6cdd76674.png)
I deleted it – Then it worked. Not a big problem, but still you may want to consider it for a future release.

then I played around a bit with it some more. I got this error:
![sequence setup](https://cloud.githubusercontent.com/assets/14355674/12537934/86379cac-c2cc-11e5-9edb-10e649acfca3.png)
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\Markus\AppData\Local\KeePass-Word-Sequencer" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   bei System.IO.Directory.GetFiles(String path, String searchPattern)
   bei Sequencer.Forms.MainForm.MainForm_Shown(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnShown(EventArgs e)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()

###############################################################

I resaved my configuration with the name I previously used ("test") wich seemed to fix it.

another bug wich i found is the following: 
if I try to use it, but didn't previously saved the default setting, it shows an error because the options.xml file doesn't exist yet. 
![error reading configuration_2](https://cloud.githubusercontent.com/assets/14355674/12538000/b4623aaa-c2cd-11e5-9343-a590fa9f83a9.png)
I think the same thing happens when you start the configuration page for the first time.

Despite this small bugs it is already useable and I appreciate your efforts very much!

**Comment by fritzophrenic** [comment]
Your "error occured reading..." message from the built-in diceware list comes from what I mentioned before, special characters need escaping. I've attached a corrected version of that file, plus an NGSL wordlist that removes the duplicate words. I'll be pushing these with some changes I'm making with the strength bar, soon.

I'm not sure, but your corrupt options.xml file may be related. Unfortunately, the easiest way past that, is probably just deleting the file.
[corrected_option_files.zip](https://github.com/fireout/keepasssequencer/files/102489/corrected_option_files.zip)

**Comment by TimetravelerDD** [comment]
thank you for the information. Just a small clarification: the options.xml was not even present in my case. I guess the error was the missing file not that it was corrupted.

**Comment by fireout** [comment]
I found what the corrupt message was, I did move some code around to structure it better and I forgot some copy paste leftovers....  

I'm not sure about the diceware problem, it seems to work fine on my end.  

I released an alpha 2 fixing at least those messages.

**Comment by TimetravelerDD** [comment]
very nice! Two more minor problems I notice:
-after loading another profile the UI does not update.
-if you try to load a profile which doesn't exist, the error message say that the file might be corrupt rather then missing

the other bugs seem to be fixed as far as I can tell.

And one more question: Why do you save the configuration in "AppData\Local" rather than "AppData\Roaming" like Keepass does?

**Comment by fritzophrenic** [comment]
> Why do you save the configuration in "AppData\Local" rather than "AppData\Roaming" like Keepass does?

I implemented that. I think it's just because I don't know the difference and I saw a reference online when I searched for where to store user-specific configurations. Do you know the difference, and/or why to choose one over the other? I'm not opposed to changing that. It's a lot better than defaulting to the installation directory like it was before I made that change :-)

**Comment by TimetravelerDD** [comment]
I agree with you.

Local stays with the user on that specific computer. Usually this data is either machine specific or too large to roam
If you are on a domain, a "roaming" profile will be uploaded before you logoff. When you log onto another computer with roaming folders, all of your files in the roaming folder will be at the new computer too. 

Doesn't make a huge difference, but the "proper" folder would probably be the roaming folder

**Comment by TimetravelerDD** [comment]
Here is another reference which i found:

Roaming. This folder **(%appdata%)** contains data that can move with your user profile from PC to PC—like when you’re on a domain—because this data has the ability to sync with a server. For example, if you sign in to a different PC on a domain, your web browser favorites or bookmarks will be available.

Local. This folder (%localappdata%) contains data that can't move with your user profile. This data is typically specific to a PC or too large to sync with a server. For example, web browsers usually store their temporary files here.

LocalLow. This folder (%appdata%/…/locallow) contains data that can't move, but also has a lower level of access. For example, if you're running a web browser in a protected or safe mode, the app will only be able access data from the LocalLow folder.

The apps themselves choose whether to save to the Local, LocalLow, or Roaming folders. Most desktop apps use the Roaming folder by default, while most Windows Store apps use the Local folder by default.

**Comment by fritzophrenic** [comment]
> I packaged the word list in the dll directly yesterday

Does this mean the XML files for the diceware list, etc. are no longer needed? I.e. is the discussion of those files on the installation wiki page now incorrect?

**Comment by fireout** [comment]
The xml files are no longer required, (I took the modification fo the wordlist files you made in [pr 25](https://github.com/fireout/keepasssequencer/pull/25))

The installation process no longer need to have does files copied either.

Sorry if this should have been more clear.

**Comment by fritzophrenic** [comment]
All issues in this are now addressed or moved to other issues, so I think this can be closed now. Right?
