### ISSUE TITLE
NGSL list contains a lot of duplicate words

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#30]
The NGSL list contains a few columns with alternate forms of each word.

We should probably only include the primary form of each word. This should result in about 2000 words.

**Comment by fritzophrenic** [comment]
The ["headwords only" list](http://www.newgeneralservicelist.org/s/NGSL-Headwords-Only-mvxw.xlsx) looks useful for this purpose.

**Comment by fritzophrenic** [comment]
A couple extra/duplicate words are in the top5k list as well. I think they do this to provide some sort of signature on the free list. Anyway there are a handful more than 5000 words in the word count. we should look at that as well.

**Comment by fritzophrenic** [comment]
Hmm, actually I'm not sure I want to remove all the alternate forms from the NGSL. What do you think, @fireout ? Is this worth doing?

Mostly my problem with this is that there are a lot of really long words in there from alternate forms. But removing them all will take the list down to something like 2800 words.

I do need to clean up both lists. The Top5k has a lot of duplicates and some non-words, bringing the total down to around 4300. The NGSL has several misspellings here and there. How do you want ot see this end up? I have a couple commits on a prune-wordlists branch where I got a start.

**Comment by fireout** [comment]
Why not have both?  A "short distinct / headword" version and the longer/full version?
Or maybe have a feature to remove similar words of any list... that might be a bit longer and a bit challenging, but I like the idea of it :)  What do you think?

I think we should fix the misspelled words
