### ISSUE TITLE
File->Load list does not refresh when saving new files

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#31]
When I save a configuration, I expect that configuration to be listed immediately in the File->Load list. It's not. Actually I can save a second configuration and neither show up.

To see the new configurations appear in the list, I need to close the configuration dialog and re-open it.

I expected the file list to refresh right after saving.

**Comment by fireout** [comment]
resolved in 7aacc9a1f572b0d35851eb62845de4343a6cd4d7
