### ISSUE TITLE
Hide full file names for saved configs?

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#32]
Proposed enhancement (feel free to close as wontfix):

Do most users care where the configurations are saved? Probably not. Why not hide the full file name in the load menu, and replace it with the configuration name, if "advanced mode" is not active? I think it would make the interface more consistent.

**Comment by fireout** [comment]
I though I had commented on this issue... Must have forgot to hit save or something.

Anyhow, it's been changed in 123b225 which is in develop already.
