### ISSUE TITLE
Need ability to delete saved configurations

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#33]
%LOCALAPPDATA% or wherever we end up saving the configurations (see #27 ) is not really a very accessible area, and won't be used manually very often. Also if we hide the full path ( #32 ) it won't be apparent where the configs are saved.

We should have an interface to remove previously saved configurations. It could mirror the KeePass profile method; load the config first, then you can delete it. Or we could have a "manage configurations" button.

**Comment by fireout** [comment]
I added a delete menu item, to delete the current configuration.

About the manage feature, we should probably only have a "explore to" options, that would browse to the folder location using the OS' file manager.

**Comment by fritzophrenic** [comment]
I'm not sure if it matters, but somehow I had a couple options XML files hanging around with no `<Name>` tag. These appears as `<Default>` in the "load" menu. These files cannot be deleted with the new delete button. Other than that, it works great!

I don't think we would need a "manage configurations" button if the delete button works. But if you think it's needed, "explore to" would be a worthwhile substitute. Maybe hide that, if the advanced options are disabled.

**Comment by fritzophrenic** [comment]
Delete feature also appears to work correctly on Ubuntu/Mono.

**Comment by fritzophrenic** [comment]
I think this issue can be closed now?

**Comment by fireout** [comment]
Sure, we can open a bug issue if the configuration with no `<Name>` still causes a problem
