### ISSUE TITLE
probability setting does not work

### ISSUE THREAD

**Issue by TimetravelerDD** [fireout/keepasssequencer#34]
there seems to by some syntax error concerning the percent probability setting.
If I try to safe the configuration I get this error:

*************\* Ausnahmetext **************
System.InvalidOperationException: Beim Generieren des XML-Dokuments ist ein Fehler aufgetreten. ---> System.InvalidOperationException: Instanzvalidierungsfehler: '30' ist kein gültiger Wert für Sequencer.Configuration.Model.PercentEnum.
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPasswordSequenceConfiguration.Write5_PercentEnum(PercentEnum v)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPasswordSequenceConfiguration.Write6_WordSequenceItem(String n, String ns, WordSequenceItem o, Boolean isNullable, Boolean needType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPasswordSequenceConfiguration.Write10_PasswordSequenceConfiguration(String n, String ns, PasswordSequenceConfiguration o, Boolean isNullable, Boolean needType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPasswordSequenceConfiguration.Write11_PasswordSequenceConfiguration(Object o)
   --- Ende der internen Ausnahmestapelüberwachung ---

**Comment by fireout** [comment]
This is actually fixed in the develop branch (see [commit](https://github.com/fireout/keepasssequencer/commit/2b954b71ba13b52e51daa8877cd1c23c71d8605e))

will be in the next release

**Comment by TimetravelerDD** [comment]
great! Thank you! when are you planning the next release?

**Comment by fireout** [comment]
I'll try to get a release by the end of next week.

I'm considering making it a beta release, @fritzophrenic what do you think?

**Comment by fritzophrenic** [comment]
Sounds good to me! I'll try to put out a pull request for my one open branch tonight. Should we include an example options.xml file in the release, like the wiki currently implies exists?

I think it would be a good idea to do that. I'd suggest a standard diceware list with 6 diceware words separated by spaces as the example file.

Sorry about that close/reopen, that was an accidental click on the button instead of the edit field.

**Comment by fireout** [comment]
I dont mind having a default xml file sitting with the binary for now, i'll create a future issue for packaging it as a resources.

**Comment by fritzophrenic** [comment]
@TimetravelerDD, have you tried the new release? Can this issue be closed, now?
