### ISSUE TITLE
Plugin information looks wrong and missing description

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#41]
The KeePass "Plugins" dialog shows "quasiVirtuel" as the author, and the description field is empty.

I think these should be populated better. I'm not sure where KeePass gets that information. Maybe the File Version Information Block? KeePass has some [conventions](http://keepass.info/help/v2_dev/plg_index.html#conventions) for this information.

![keepass_seq_plugin_info](https://cloud.githubusercontent.com/assets/1334420/13501814/bf847500-e12d-11e5-8320-8bb7ca7bd269.png)

**Comment by fireout** [comment]
This information is stored in Properties/AssemblyInfo.cs.

I'll update the values now

**Comment by fritzophrenic** [comment]
Looks good! What do you think about creating tags on develop branch corresponding to releases?

**Comment by fireout** [comment]
I was thinking moving everything to master first, and then tag master.

I should have probably move everything with the release though, come to think of it.
