### ISSUE TITLE
Support multiple saved configurations

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#5]
Feature request: allow saving a configuration with an associated name, for later recall. Thus you could have one configuration for diceware, one for the alternate diceware list, one for secure sites that need 10 words, one for sites where 5-6 words is plenty, etc.

Bonus points: add these configurations as separate custom algorithms or generators, so that they can be accessed without even going into the settings dialog for WordSequencer.

I'm not sure how to mark this as a feature request/enhancement, maybe I don't have appropriate access rights to do that.

**Comment by fireout** [comment]
Enhancement is set through the labels section (at the right).  Not sure either if you needed to be a collaborator to be able to edit, but I added you as a collaborator.

**Comment by fritzophrenic** [comment]
Awesome, thank you!

**Comment by fritzophrenic** [comment]
FYI: the reason I want these configurations available to select outside of the Sequencer config screen, is so that I can store the config to use in a KeePass password profile.

**Comment by fireout** [comment]
I was going to add a File menu with Load/Save features... I'm all for it being compatible with the password profiles, but I haven't found much on the matter... How does KeePass manage to pass the config/profile to the plugin?

**Comment by fritzophrenic** [comment]
I meant that I want to be able to select a saved configuration, then save a profile that will use that profile. I have not tried but I _assume_ you can save a profile with a selected custom algorithm, and use it to generate with that algorithm. So I assume adding a custom algorithm name will allow saving profiles.

**Comment by fritzophrenic** [comment]
I like the way this works now, especially with the updates to the wiki's [File Menu page](2.1-Basic-Configuration—File-menu#association-with-keepass-profiles). I think this issue can probably be closed.
