### ISSUE TITLE
Add setting to retrieve word list from .txt file

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#6]
I understand the current size of a word list that can be entered into the GUI is limited by constraints on the GUI element, not by the code.

Additionally, sharing word lists, or switching between them, can be difficult.

Easy solution for all of these: provide a control to select the source of a word list between the GUI text entry field, and a text file. The config would only need to store the file path, and the word list would be read from that file whenever the config is loaded.

Then the plugin files could include some common word lists in the distribution, as well.

This control should be replicated for the custom word lists for individual sequence entries.

**Comment by fritzophrenic** [comment]
> The config would only need to store the file path, and the word list would be read from that file whenever the config is loaded.

Actually I'm working on a fix where you can just load a word list from a text file similar to the recently added feature for appending words from built-in lists. I think that makes the interface much cleaner. I'm overcoming text box limitations by increasing max length when the box is full.

If storing the file path is better instead, let me know.

**Comment by fireout** [comment]
Loading the words from a file like it's currently done is probably the easiest way, but if the file gets changed afterward, it wont "reload" the word list... unless it's re"imported" using the form.

Storing the file path is better for that it will always reload any changes to the file, but if the file ends up missing, we will end up with no words.  It is also probably something that will take longer to implement...

So, I think, both options have good and bad...  it's up to you...   I dont mind the shorter path for now, we could implement storing the file path later, and maybe even have both options living together...

**Comment by fritzophrenic** [comment]
I pushed an implementation of a "load from file" feature in my [load-from-file branch](https://github.com/fritzophrenic/keepasssequencer/tree/load-from-file). Do you want me to merge in your "advanced config" stuff before I create a pull request? I can try that out later this week.

I wanted to share code between the override list and the default word list for adding words from files/built in lists, but I couldn't think of a very elegant way to do it. Maybe creating a new class that takes a text box to operate on in its constructor, and a method to append words from a given list.

But the way it is now works fine, it just duplicates a little bit of code.

**Comment by fireout** [comment]
Sure, merge the branch first.

The duplicated code is fine for now.  I eventually want to restructure a good part of the classes to make it more solid, it includes the serialization that is within the model now... restructuring this will definitly require to also change the WordList/OverridableList...

I'll wait for your comment on the advanced-config stufff, thanks,
